# in your terminal, run conda: conda env create -f environment.yml
name: bw_panel
channels:
  - conda-forge
  - cmutel
  - diepers
dependencies:
  - brightway25_nosolver # uncomment for macOS ARM machines
  - scikit-umfpack # uncomment for macOS ARM machines
  - numpy==1.24 # uncomment for macOS ARM machines
  - panel
  - plotly
  - pip:
    - panel-material-ui
